
GET http://localhost:6969/api/auth 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJVU0VSMSIsImlhdCI6MTY4MzYyNTAyNn0.TYza9tvcA2pmBm_qtv4p0qkZBSLZhULfiCcYU-qOiVE

###
POST http://localhost:6969/api/auth/login 
content-type: application/json

{
"username":"user2",
"password":"1"
}
